### ISSUE TITLE
Backport to 1.20.1

### ISSUE THREAD

**Issue by duarm** [AnOpenSauceDev/Weight#10]
Thanks for making this mod!

Since 1.20.1 is the most well supported version, would it it be too much trouble to backport new releases to 1.20.1?

**Comment by AnOpenSauceDev** [comment]
I would love to support 1.20.1, but the whole point of the newer releases is that I've upgraded the API to support [custom functions for every weight definition](https://github.com/AnOpenSauceDev/Weight/wiki/Custom-Datapack-Integration). I can't backport because said features rely on relatively new (1.20.3+) functionality for datapacks.

 Aside from that, you're only missing out on the new armour bar renderer and a few other very minor changes.
